services:
  postgres:
    image: postgres:16-alpine
    container_name: journly-postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: journly
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
